spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

app:
  payments:
    stripe:
      webhook-secret: ${PAYMENT_STRIPE_WEBHOOK_SECRET}
