spring:
  application:
    name: mobiletech

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
  storage:
    region: ${STORAGE_REGION}
    access-key: ${STORAGE_ACCESS_KEY}
    secret-key: ${STORAGE_SECRET_KEY}
    endpoint: ${STORAGE_ENDPOINT}
    bucket-name: ${STORAGE_BUCKET_NAME}
    bucket-prefix-products: ${STORAGE_BUCKET_PREFIX_PRODUCTS}
  payments:
    paypal:
      client-id: ${PAYMENT_PAYPAL_CLIENT_ID}
      client-secret: ${PAYMENT_PAYPAL_CLIENT_SECRET}
      mode: ${PAYMENT_PAYPAL_MODE}
      redirect-url: ${PAYMENT_PAYPAL_REDIRECT_URL}
      cancel-url: ${PAYMENT_PAYPAL_CANCEL_URL}
    stripe:
      secret-key: ${PAYMENT_STRIPE_SECRET_KEY}
      webhook-secret: ${PAYMENT_STRIPE_WEBHOOK_SECRET}
