spring:
  application:
    name: mobiletech

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/mobiletech
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
